spring.application.name=api-gateway
server.port=8080

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Routes MVC
spring.cloud.gateway.mvc.routes[0].id=module-competence
spring.cloud.gateway.mvc.routes[0].uri=lb://module-competence
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/module_competence/**

spring.cloud.gateway.mvc.routes[1].id=module-portfolio
spring.cloud.gateway.mvc.routes[1].uri=lb://module-portfolio
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/module_portfolio/**

spring.cloud.gateway.mvc.routes[2].id=module-certification
spring.cloud.gateway.mvc.routes[2].uri=lb://module-certification
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/module_certification/**